# Generated by Django 5.2.9 on 2025-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusers',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
