# Generated by Django 5.2.9 on 2026-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measurement_unit', models.CharField(max_length=50)),
                ('opening_stock', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('current_stock', models.BigIntegerField()),
            ],
        ),
    ]
