# Generated by Django 5.2.9 on 2026-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebarItems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcard',
            name='date',
        ),
        migrations.AddField(
            model_name='stockcard',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='description',
            field=models.TextField(),
        ),
    ]
